// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.2
// source: fulfillment.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FulfillmentClient is the client API for Fulfillment service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FulfillmentClient interface {
	AssignedOrder(ctx context.Context, in *AssignedOrderRequest, opts ...grpc.CallOption) (*AssignedOrderResponse, error)
	UpdateStatus(ctx context.Context, in *UpdateStatusRequest, opts ...grpc.CallOption) (*UpdateStatusResponse, error)
}

type fulfillmentClient struct {
	cc grpc.ClientConnInterface
}

func NewFulfillmentClient(cc grpc.ClientConnInterface) FulfillmentClient {
	return &fulfillmentClient{cc}
}

func (c *fulfillmentClient) AssignedOrder(ctx context.Context, in *AssignedOrderRequest, opts ...grpc.CallOption) (*AssignedOrderResponse, error) {
	out := new(AssignedOrderResponse)
	err := c.cc.Invoke(ctx, "/FulfillmentService.fulfillment/AssignedOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fulfillmentClient) UpdateStatus(ctx context.Context, in *UpdateStatusRequest, opts ...grpc.CallOption) (*UpdateStatusResponse, error) {
	out := new(UpdateStatusResponse)
	err := c.cc.Invoke(ctx, "/FulfillmentService.fulfillment/UpdateStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FulfillmentServer is the server API for Fulfillment service.
// All implementations must embed UnimplementedFulfillmentServer
// for forward compatibility
type FulfillmentServer interface {
	AssignedOrder(context.Context, *AssignedOrderRequest) (*AssignedOrderResponse, error)
	UpdateStatus(context.Context, *UpdateStatusRequest) (*UpdateStatusResponse, error)
	mustEmbedUnimplementedFulfillmentServer()
}

// UnimplementedFulfillmentServer must be embedded to have forward compatible implementations.
type UnimplementedFulfillmentServer struct {
}

func (UnimplementedFulfillmentServer) AssignedOrder(context.Context, *AssignedOrderRequest) (*AssignedOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssignedOrder not implemented")
}
func (UnimplementedFulfillmentServer) UpdateStatus(context.Context, *UpdateStatusRequest) (*UpdateStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStatus not implemented")
}
func (UnimplementedFulfillmentServer) mustEmbedUnimplementedFulfillmentServer() {}

// UnsafeFulfillmentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FulfillmentServer will
// result in compilation errors.
type UnsafeFulfillmentServer interface {
	mustEmbedUnimplementedFulfillmentServer()
}

func RegisterFulfillmentServer(s grpc.ServiceRegistrar, srv FulfillmentServer) {
	s.RegisterService(&Fulfillment_ServiceDesc, srv)
}

func _Fulfillment_AssignedOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignedOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FulfillmentServer).AssignedOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FulfillmentService.fulfillment/AssignedOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FulfillmentServer).AssignedOrder(ctx, req.(*AssignedOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fulfillment_UpdateStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FulfillmentServer).UpdateStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FulfillmentService.fulfillment/UpdateStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FulfillmentServer).UpdateStatus(ctx, req.(*UpdateStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Fulfillment_ServiceDesc is the grpc.ServiceDesc for Fulfillment service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Fulfillment_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "FulfillmentService.fulfillment",
	HandlerType: (*FulfillmentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AssignedOrder",
			Handler:    _Fulfillment_AssignedOrder_Handler,
		},
		{
			MethodName: "UpdateStatus",
			Handler:    _Fulfillment_UpdateStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fulfillment.proto",
}
